version: '3.8'
services:
  vault:
    image: hashicorp/vault:1.15
    container_name: vault
    ports:
      - "8200:8200"
      - "8201:8201"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_ADDR=https://0.0.0.0:8200
      - VAULT_SKIP_VERIFY=true
      # Add multiple SANs
      - VAULT_DEV_TLS_SAN=vault.demo,localhost,127.0.0.1
      # Add DNS alias
      - VAULT_DEV_TLS_CERT_SANS=vault.demo
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault/config:/vault/config
      - ./vault/data:/vault/data
      - ./vault/certs:/vault/certs
    command: server -dev -dev-tls -dev-root-token-id="root" -dev-tls-san=vault.demo
    networks:
      kind:
        aliases:
          - vault.demo
      vault-network: {}
    healthcheck:
      test: ["CMD", "vault", "status", "-tls-skip-verify"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  vault-network:
  kind:
    external: true
    name: kind