apiVersion: v1
kind: ConfigMap
metadata:
  name: client-spiffe-helper-config
  namespace: app
data:
  helper.conf: |
    agent_address = "/run/spire/agent-sockets/spire-agent.sock"
    cert_dir = "/run/spiffe/certs"
    svid_file_name = "svid.pem"
    svid_key_file_name = "svid_key.pem"
    svid_bundle_file_name = "svid_bundle.pem"