apiVersion: v1
kind: ServiceAccount
metadata:
  name: spire-server
  namespace: spire
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::164314285563:role/SpireServerRole
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spire-agent
  namespace: spire