apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: app
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: postgres
  namespace: app
subsets:
  - addresses:
      - ip: POSTGRES_IP
    ports:
      - port: 5432